//            File: UniNodeMemWrapper.tempconf.h
// Original Author: Michael Imelfort
// --------------------------------------------------------------------
//
// OVERVIEW:
// This file stores all the possible readlengths we'll compile for
// with respect to the uninode object
// To add a new readlength you need to add 2 lines here. If the new
// readlength is foo bases then add:
// 
//    MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,FOO,iNSTaNCeOFF,12); 
//    MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,FOO,iNSTaNCeOFF,4); 
// 
// also you must ensure that the readlengths foo, foo - 4 and foo - 12 are
// all implemented in ReadNodeMemWrapper.tempconf.h
// Enjoy!
// 
// --------------------------------------------------------------------
// Copyright (C) 2009 2010 2011 Michael Imelfort and Dominic Eales
//
// This file is part of the Sassy Assembler Project.
//
// Sassy is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sassy is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Sassy.  If not, see <http://www.gnu.org/licenses/>.
// --------------------------------------------------------------------
//
//                        A
//                       A B
//                      A B R
//                     A B R A
//                    A B R A C
//                   A B R A C A
//                  A B R A C A D
//                 A B R A C A D A
//                A B R A C A D A B 
//               A B R A C A D A B R  
//              A B R A C A D A B R A 
//
// readLengths supported:
// 25 : 2 : 99
//
// offsets supported:
// 2 : 2 : 16
//
#ifndef UniNode_TEMPLATES
    #define UniNode_TEMPLATES

#if 0
#define makeAppropriateUniNodeMemWrapper(oBJpOINTER,iNSTaNCeRL,iNSTaNCeOFF) { \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,12); \
}
#else
    
#define makeAppropriateUniNodeMemWrapper(oBJpOINTER,iNSTaNCeRL,iNSTaNCeOFF) { \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,25,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,27,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,29,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,31,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,33,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,35,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,37,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,39,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,41,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,43,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,45,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,47,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,49,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,51,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,53,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,55,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,57,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,59,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,61,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,63,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,65,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,67,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,69,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,71,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,73,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,75,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,77,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,79,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,81,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,83,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,85,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,87,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,89,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,91,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,93,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,95,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,97,iNSTaNCeOFF,16); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,2); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,4); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,6); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,8); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,10); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,12); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,14); \
MAKE_UNINODEMEMWRAPPER(oBJpOINTER,iNSTaNCeRL,99,iNSTaNCeOFF,16); \
}
#endif
#endif // uninode_TEMPLATES
